import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { ShopContextProvider } from "@/context/shopContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-50">
        <div>
          <ShopContextProvider>
            <Navbar />
            {children}
            <Footer />
          </ShopContextProvider>
        </div>
      </body>
    </html>
  );
}
